In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('student_performance.csv')

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
df.shape[0]

30

In [ ]:
df.shape[0:6]

(30, 13)

In [ ]:
print(df.name.tolist())

['Aarav Sharma', 'Priya Patel', 'Rohit Verma', 'Sneha Reddy', 'Arjun Nair', 'Meera Joshi', 'Kiran Kumar', 'Divya Singh', 'Rahul Mishra', 'Ananya Das', 'Vikram Iyer', 'Pooja Gupta', 'Suresh Rao', 'Kavya Nambiar', 'Ajay Tiwari', 'Ritu Agarwal', 'Manoj Pandey', 'Swati Kulkarni', 'Deepak Chauhan', 'Nisha Kapoor', 'Harish Pillai', 'Tanvi Mehta', 'Sanjay Dubey', 'Preeti Saxena', 'Amit Bose', 'Rekha Nair', 'Gaurav Shukla', 'Sunita Pillai', 'Nitin Jain', 'Akanksha Yadav']

In [ ]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
df = df[df['math_score'] != 5]

In [ ]:
df = df.fillna(df.mean(numeric_only=True))

In [ ]:
df=df.dropna()

In [ ]:
display(df)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
df=df[df['math_score']!=5]
display(df.head())

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
print(df['department'].value_counts())

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
print(df['gender'].value_counts())

gender
Male      15
Female    15
Name: count, dtype: int64

In [ ]:
print(df['city'].value_counts())

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [ ]:
Mechanicalstd=df[df['department']=='Mechanical']
print(f"number Mechanical std: {len(Mechanicalstd)}")

number Mechanical std: 6

In [ ]:
print(df[df['programming_score']=='mumbai'])

Empty DataFrame
Columns: [student_id, name, age, gender, department, semester, math_score, science_score, english_score, programming_score, attendance_percentage, city, admission_year]
Index: []

In [ ]:
chennai_students = df[df['city'] == 'Chennai']
display(chennai_students[['name', 'math_score', 'science_score', 'english_score', 'programming_score']])

In [ ]:
city_students = df[(df['city'] == 'Chennai') | (df['city'] == 'Mumbai')]
display(city_students[['name', 'programming_score']])

            name  programming_score
0   Aarav Sharma                 91
10   Vikram Iyer                 72

In [ ]:
city_students_and = df[(df['city'] == 'Chennai') & (df['city'] == 'Mumbai')]
display(city_students_and[['name', 'programming_score']])

Empty DataFrame
Columns: [name, programming_score]
Index: []

In [ ]:
high_att=df[df['attendance_percentage']<=75]
print(high_att)

    student_id           name  age  gender        department  semester  \
5         1006    Meera Joshi   20  Female       Electronics         2
8         1009   Rahul Mishra   20    Male        Mechanical         2
14        1015    Ajay Tiwari   19    Male  Computer Science         2
16        1017   Manoj Pandey   21    Male             Civil         2
20        1021  Harish Pillai   20    Male       Electronics         2
22        1023   Sanjay Dubey   21    Male             Civil         2
27        1028  Sunita Pillai   19  Female             Civil         2

    math_score  science_score  english_score  programming_score  \
5           58             66             70                 52
8           62             71             58                 45
14          71             69             64                 76
16          56             61             55                 38
20          64             70             67                 58
22          61             66             59                 42
27          60             65             68                 39

    attendance_percentage                city  admission_year
5                      72                Pune            2023
8                      68            Varanasi            2023
14                     75              Bhopal            2023
16                     65               Patna            2023
20                     74  Thiruvananthapuram            2023
22                     70           Allahabad            2023
27                     73  Thiruvananthapuram            2023

In [ ]:
display(df['attendance_percentage'])

0     92
1     87
2     78
3     95
4     90
5     72
6     85
7     96
8     68
9     98
10    83
11    80
12    88
13    91
14    75
15    93
16    65
17    94
18    77
19    89
20    74
21    97
22    70
23    86
24    91
25    82
26    87
27    73
28    84
29    95
Name: attendance_percentage, dtype: int64

In [ ]:
df['tot']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
display(df['tot'])

0     326
1     325
2     255
3     273
4     356
5     246
6     247
7     356
8     236
9     371
10    295
11    262
12    334
13    285
14    280
15    325
16    210
17    354
18    252
19    327
20    259
21    367
22    228
23    287
24    336
25    285
26    325
27    232
28    271
29    365
Name: tot, dtype: int64

In [ ]:
least=df.loc[df['tot'].idxmin()]
print(least)

student_id                       1017
name                     Manoj Pandey
age                                21
gender                           Male
department                      Civil
semester                            2
math_score                         56
science_score                      61
english_score                      55
programming_score                  38
attendance_percentage              65
city                            Patna
admission_year                   2023
tot                               210
Name: 16, dtype: object